# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 078180aff2bef1b2b4af2e6e49f23beaff34e00aec2450bea8beaadc87fd3fa7db5167de3cceb3dc7268e675013677d4897225ee27168d772c6707bf1090a347

test:
  secret_key_base: 341a150d7281d320e9cfebbef5ccb8fcf8466c80d7f2d026e03df7b3bd7529c6d7379fc054ef0e7867aa8cdd8e23295269be60a7214fb39298ffc902e4a05334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
